name: Docker Build

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push market sentiment image
        uses: docker/build-push-action@v5
        with:
          context: ./gct-market-sentiment
          push: true
          tags: ghcr.io/${{ github.repository }}/sentiment:latest
      - name: Build and push moderation image
        uses: docker/build-push-action@v5
        with:
          context: ./soulmath-moderation-system
          push: true
          tags: ghcr.io/${{ github.repository }}/moderation:latest
